# analyze BD graphs

require(ggplot2)
require(data.table)

paper_mode=TRUE
source('R/helper.R')


######### general section ################################
r_data = read.csv(unz(description = "../data/BD/choices_diagno.csv.zip", filename = 'choices_diagno.csv'))
r_data$ID = as.character(r_data$ID)
r_data$key = as.character(r_data$key)
r_data[r_data$key == "R1",]$key = 1
r_data[r_data$key == "R2",]$key = 2
r_data$group = r_data$diag

require(plyr)
r_data$n_choice = ddply(r_data, c("ID", "trial"), function(x){data.frame(n_choice=1:nrow(x))})$n_choice

library("RColorBrewer")
cols <- brewer.pal(n = 4, name = palette_mode)


library(grid)
element_grob.element_custom <- function(element, ...)  {

  segmentsGrob(c(1,0,0),
               c(0,1,0),
               c(0,1,0),
               c(0,1,0), gp=gpar(lwd=4, col=col[4]))
}
## silly wrapper to fool ggplot2
border_custom <- function(...){
  structure(
    list(...), # this ... information is not used, btw
    class = c("element_custom","element_blank", "element") # inheritance test workaround
  )

}

for (gr in c('Healthy', 'Depression', 'Bipolar')){
    sub_data = subset(r_data, diag == gr)
    ggplot(sub_data, aes(x = n_choice, y = key, group = "1")) +
      geom_line(color='black', size=0.2) +
      guides(fill = guide_legend(keywidth = 0.5, keyheight = 3.0)) +
      blk_theme_nothing(margins = c(1,1,1,1))  +
      theme(panel.background = element_rect(fill = "white")) +
      theme(panel.background = border_custom()) +
      theme(axis.line = element_blank()) +
      facet_grid(ID ~ trial)

    ggsave(paste0("../doc/graphs/plots/choice_", gr, ".pdf"),
           width=6, height=6, units = "in")
}


########## for presentation #############################
######### general section ################################
r_data = read.csv(unz(description = "../data/BD/choices_diagno.csv.zip", filename = 'choices_diagno.csv'))
r_data$ID = as.character(r_data$ID)
r_data$key = as.character(r_data$key)
r_data[r_data$key == "R1",]$key = 1
r_data[r_data$key == "R2",]$key = 2
r_data$group = r_data$diag

require(plyr)
r_data$n_choice = ddply(r_data, c("ID", "trial"), function(x){data.frame(n_choice=1:nrow(x))})$n_choice

sub_data = subset(r_data, diag == "Bipolar")
ggplot(sub_data, aes(x = n_choice, y = key, group = "1")) +
  geom_line(color="red") +
  scale_fill_brewer(name = "", palette="Set1", labels = c("X0", "X1")) +
  guides(fill = guide_legend(keywidth = 0.5, keyheight = 3.0)) +
  blk_theme_no_lablel(legend_position = "right")  +
  facet_grid(ID ~ trial)

ggsave("../nongit/graphs/BD/choices.pdf",  width=40, height=25, units = "cm")

######### number of trials in each condition #######################

# note that this file is not included in nongit folder and is generated by the python code
resp_block = read.csv("../nongit/results/local/no_trial.csv")

require(plyr)

resp_block$sum_cont = resp_block$prop0 + resp_block$prop1
props = ddply(resp_block, c("group", "sum_cont"), function(x){data.frame(resp = mean(x$choices), con = paste("[", x[1,]$prop0, ", ", x[1,]$prop1, "]", sep=""))})
write.csv(props, 'props.csv')